# Introducción a las herramientas del cómputo científico.

Sergio A. Alcalá Corona <br>
Sergio A. Sánchez Chávez

---
---

# PROGRAMACIÓN EN PYTHON

## Interprete de comandos python e ipython.

En este *Notebook* presentaremos de manera breve el interprete de comandos de python y algunas ...




---


## Python

**Python** es un interprete de comandos que se ejecuta en una terminal de linux. En este se escriben comandos como **entrada** y el interprete regresa una respuesta como **salida**.

Es muy similar a otros interpretes de comandos como el shell de de linux o *gnuplot*. 

Además se puede utilizar para realizar computo científico de una manera muy similar a algunos interpretes de comandos muy populares como **MathLab**, **Mathematica** o **Maple**.

Además de esto Python puede guardar datos como texto o valores numéricos en variables.

Así como utilizar estructuras de control, lo que permite realizar instrucciones repetidamente o evaluar valores para poder tomar decisiones.

De esta manera al igual que en *MathLab*, *Mathematica* o *Maple*, se pueden escribir scripts para  realizar cálculos de computo científico, ya que dispone de un extenso numero de librerías (o bibliotecas) diseñadas para realizar fácilmente diferentes tareas.

Así *Python* no solo es un interprete de comandos, sino un lenguaje de programación (interpretado), que por si fuera poco es orientado a objetos, ya que las bibliotecas y funciones que se pueden construir permiten programarse y usarse bajo este paradigma.

A pesar de su gran **robustez** y versatilidad Python es un lenguaje muy fácil de  aprender y de usar. Por lo que es ideal para comenzar a programar y como una herramienta eficaz para acercarse por primera vez al computo científico.

### *Ipython* y celdas de Jupyter

**ipython** (*Interactive Python*) es un interprete de Python pero mucho mas robusto que el nativo (y es la base de los cuadernos de *Jupyter*), está diseñado para maximizar la productividad al utilizar Python. Aquí podemos encontrar ciertas facilidades, utilidades y comandos que no existen en otros interpretes de Python.

Por ejemplo completar palabras parciales con la tecla <TAB>, o bien podemos ejecutar un comando del shell de linux anteponiendo el símbolo `!`

In [1]:
!pwd

/home/sergio/Dropbox/CursoComputacion2020/Preparacion/PythonJupyterNotebooks


In [2]:
!ls

3_LINUX_Procesos-Compresion-y-ConeccionRemota.ipynb
BitacoraDeHoy.py
Potencia.ipynb
Python_interprete_de_comandos.ipynb


Además, se cuenta con los comandos `who` y `whos` que proveen información de las funciones nuevas agregadas en la sesión.

Así también, la documentación de cualquier función o comando está disponible al poner `?`, por ejemplo:

In [3]:
who?

Y para funciones, se puede consultar código fuente de estas (cuando está disponible) usando `??` .

In [4]:
range??

### Bitacora

Cuando usemos el entorno `Ipyton` es posible guardar una **bitacora** (*log*) de la sesión. Esto se logra mediante el comando `logstart`.

In [5]:
logstart  BitacoraDeHoy.py

Activating auto-logging. Current session state plus future input saved.
Filename       : BitacoraDeHoy.py
Mode           : backup
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


Al ingresar el comando `logstart`, seguido del *nombre del archivo* que le queramos poner, todo lo que se teclea en la sesión de `Ipyton` se guarda (incluso los fallos) dentro del archivo, en este caso el archivo donde se guarda todo se llama   `BitacoraDeHoy.py`, pero se puede llamar de cualquier forma.

## BIBLIOTECAS

La gran versatilidad de python vine dada en gran parte por el conjunto de **bibliotecas** que este ya tiene incorporadas, así que hay que aprovechar lo que ya esta hecho! Por ejemplo:

* `python-numpy` **librería de arreglos matemáticos**


* `python-scipy` **rutinas para uso científico**


* `python-matplotlib` **gráficas en 2 dimensiones**


* `python-pandas` **para manejo de DataFrames**


* `python-visual` **animaciones en 3 dimensiones**


* `mayavi2`

Para instalar *bibliotecas* en python podemos correr desde la Terminal (*bash*) el siguiete comando

`python -m pip install` *`BIBLIOTECA`*

Python cuenta una biblioteca estándar amplia, lo cual siempre está disponible en cualquier instalación de Python.

La documentación para esta biblioteca está disponible en http://docs.python.org/library/

Sin embargo para poder hacer un uso mucho más amplio y poderoso de python se puede hacer uso del resto de las bibliotecas disponibles una vez que estén instaladas. Por ejemplo para llevar a cabo cálculos con funciones más avanzadas, es necesario **importar** la biblioteca estándar de matemáticas `math`.

Así ya instaladas se puede hacer uso de las bibliotecas **importándolas**, para que *python* sepa que las debe usar.

Para esto se debe dar una instrucción especial (*sentencia de importación*) para que python (ya sea en el *interprete de comandos*, `Ipython`, `Jupyter` bien en un *script*) pueda acceder a ellas.

Para poder usar una biblioteca (o parte de ella) simplemente se tiene que indicar que biblioteca estamos llamando e importar de ella lo que vamos a usar.

Por ejemplo:

In [6]:
from fractions import Fraction

Aquí se está importando la función `Fraction` de la biblioteca `fractions` (que está en la sección 9 de la biblioteca estándar). O bien:

In [9]:
from math import *

Aquí se está importando **todas** las funciones de las bibliotecas `math` y de la biblioteca `visual`.

**NOTA**: Cuando llamamos una función de una biblioteca que no está instalada o no se ha importado python nos reportará un error.

También se puede importar parcialmente una biblioteca. Es decir, sólo la sub-biblioteca que nos interese, para ser el código más eficiente. Por ejemplo:

In [10]:
from scipy import stats

Y también se puede importar la biblioteca bajo un *alias* que la contenga, por ejemplo:

In [11]:
import pandas as pd

Como ya se menciono *Python* es tan poderoso pues es lenguaje **orientado a objetos**.

Cada *"cosa"* en *Python* es un **objeto**, que tiene propiedades y operaciones disponibles (**métodos**). 

Por ejemplo, `Fraction` es un tipo de objeto (**clase**); sus operaciones están disponibles en *Ipython* a través de `Fraction.<TAB>`. 

Las que empiezan con `__` son internos y deberan de ignorarse por el momento; las demás son accesibles al usuario.

In [ ]:
Fraction.

In [13]:
pd.

## Manejo de Información

Python (ya sea mediante el interprete de comandos o bien mediante el entorno *Ipython* o *Jupyter*) nos permite resolver problemas y realizar operaciones matemáticas de una manera  interactiva, en la que se ejecutan comandos (entrada) y *python* a su vez da una respuesta (salida) en el mismo momento. De esta manera, *python* se puede usar como si fuera una **calculadora** muy potente.

De esta manera podemos realizar funciones aritméticas usando los operadores que ya se han mencionado y que son estándares en casi todos los lenguajes de programación Suma (`+`), Resta (`-`), Producto (`*`), División (`/`).

### ARITMÉTICA

In [41]:
3 + 2

278.70000000000005

In [44]:
3 * (-7.1 + 10**2)

278.70000000000005

Aquí `**` indica una potencia, y los paréntesis alteran la prioridad en las operaciones.

**OJO!!**: Es necesario tener cuidado al hacer manipulaciones con enteros como en:

In [45]:
1/2

0

In [46]:
3/2

1

ya que el resultado se redondea al entero más cercano. Para evitar eso, basta un punto decimal:

In [47]:
1/2.

0.5

Los números sin punto decimal se consideran enteros, y los con punto decimal flotantes (de doble precisión).

Los enteros pueden ser arbitrariamente grandes:

In [60]:
a = 2 ** 2 ** 2 ** 2 ** 2

Python también cuenta con números complejos, utilizando la notación `1j` para la raiz de `−1`:

In [61]:
1 + 3j

(1+3j)

In [62]:
1j * 1j

(-1+0j)

In [99]:
j # sólito, da un error

`#` indica un comentario (no se lee, por lo que no cuenta) que se extiende hasta el final de la línea.

In [73]:
# Esto es un "comentario" (no se lee, por lo que no cuenta) que se extiende hasta el final de la línea.

*Python* también oincluye de forma natova varialbles para número irracionales muy usados como $e$ y $\pi$:

In [14]:
e

2.718281828459045

In [15]:
pi

3.141592653589793

### VARIABLES

Para llevar a cabo cálculos, necesitamos **variables**.
Las variables se declaran sin **necesidad de indicar su tipo de dato** (entero, flotante, etc.):

In [75]:
a
a = 3
b = 17.5
c = 1 + 3j

print a + b / c

(4.75-5.25j)


Python reconoce de manera automática el tipo de la variable según su forma. 

El comando **`print`** imprime el argumento (valor interior) de la variable.

Recordemos que el símbolo `=` **no es equivalente al símbolo igual en matemáticas**, en programación este símbolo significa **asignación** (es decir, guardar un valor en una variable) y asimismo sirve para reasignarle un valor a la misma. 

En python, al reasignar una variable, se pierde la información de su valor interior, incluyendo el tipo:

In [76]:
a = 3
a = -5.5

Por lo que hay que tener cuidado al usar el el símbolo `=` para no perder información.

#### Conversión entre tipos de datos.

Aunque no haya que declararlos al definir variables, hay distintos tipos de números en Python, principalmente enteros (**`int`**) y flotantes (**`float`**).

Para convertir entre diferentes tipos, incluyendo cadenas, podemos utilizar:

In [25]:
a = float(3)

pi_short = float('3.1416')
Mypi = int(pi_short)

b = int(17.)

edad = int("19")

year = str(1998)

In [18]:
a

3.0

In [19]:
pi_short

3.1416

In [20]:
Mypi

3

In [21]:
type(Mypi)

int

In [22]:
edad

19

In [23]:
type(edad)

int

In [26]:
year

'1998'

In [28]:
type(year)

str

In [27]:
len(year)

4

Las cadenas en Python son cadenas de caracteres entre apóstrofes o comillas.

In [26]:
"hola"
'mi edad es: '

'mi edad es: '

se pueden concaternar cadenas usado el simbolo `+`

In [33]:
cadena = "hola " + 'mi edad es: '

In [34]:
cadena

'hola mi edad es: '

In [35]:
len(cadena)

17

#### Aritmética con precisión arbitraria.

A veces, es necesario poder llevar a cabo operaciones aritméticas con números flotantes (*reales*) con precisión superior a los **16 dígitos** que provee el **float** (número de **doble precisión**) de Python. Para hacerlo, existen varios proyectos que proveen bibliotecas con este fin.

Una opción, la biblioteca **`mpmath`**, que está escrita completamente en Python. En principio eso lo hace más lento, pero más fácil de entender y modificar el código.

Para cargar la biblioteca, hacemos:

In [ ]:
from mpmath import *

## Arreglos

En Python hay 3 tipos diferentes de arreglos. Las **listas**, las **n-adas** (o tuples) y los **arreglos numpy**, estos últimos son mas robustos y con ellos se puede representar vectores e incluso matrices.

### Listas

La estructura de datos principal en Python es la lista. Consiste literalmente en una lista ordenada de cosas, y
reemplaza a los arreglos en otros lenguajes. La diferencia es que las listas en *Python* son automáticamente de longitud variable, y pueden contener objetos de cualquier tipo.

Una lista se define entre corchetes (`[y]`):

In [49]:
l = [3, 4, 6]

Puede contener cualquier cosa, ¡incluyendo a otras listas!:



In [50]:
l2 = [3.5, -1, "hola", [1.0, [3, 17]]]

Los elementos de la lista se pueden extraer y cambiar usando la notación `lista[`*`i`*`]`, donde *`i`* indica el número del elemento, empezando desde `0`:



In [51]:
l3 = [1, 2, 3]
print l3[0], l3[1]

1 2


Y así también se pueden reasignar sus valores: 

In [54]:
l[0] = 5
l

[5, 4, 6]

Tambipen Se pueden manipular rebanadas (“*slices*”) de la lista con la notación l[1:3]:

In [55]:
ls = [1, 2, 3, 6, 7]

In [56]:
ls[1:3]

[2, 3]

In [57]:
ls[:3]

[1, 2, 3]

In [58]:
ls[3:]

[6, 7]

La longitud de una lista se puede encontrar con `len(`*`lista`*`)`:

In [61]:
len(ls)

5

Se pueden agregar elementos a la lista con:

In [62]:
l = [] # lista vacía
l.append(17)
l.append(3)

In [63]:
print l, len(l)

[17, 3] 2


Como siempre, las otras operaciones que se pueden llevar a cabo con la lista se pueden averiguar en ipython con:
`l.<TABULADOR>`

In [ ]:
l.

### La función *range()*

Para averiguar que es lo que hace una función, se puede investigar de manera interactiva:

In [64]:
range??

`range(N)` devuelve una lista que contiene una progresión aritmética de enteros.

In [65]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Nótese que la lista comienza en 0 (cero) y que se omite el elemento final, por ejemplo `range(4)` es una lista de cuatro elementos que llega hasta el 3.

In [66]:
range(4)

[0, 1, 2, 3]

También se le puede indicar en donde inicia y donde termina la lista:

In [67]:
range(3,10)

[3, 4, 5, 6, 7, 8, 9]

O bien también se le puede indicar un paso de incremento:

In [68]:
range(3,17,2)

[3, 5, 7, 9, 11, 13, 15]

In [69]:
range(3,17,3)

[3, 6, 9, 12, 15]

In [70]:
range(3,17,5)

[3, 8, 13]

También nótese que range no acepta argumentos de punto flotante.

In [72]:
range(3.,10.)

## Arreglos numpy (vectores).

Por lo general las listas y *tuples* se utilizan para guardar y manipular datos. Sin embargo, las listas no se comportan como vectores, y menos como matrices (al sumarlos no se comportan de la manera adecuada, etc.). El propósito de la biblioteca numpy es justamente el de proporcionar objetos que representan a vectores y matrices matemáticos, con todas las bondades que traen consigo este tipo de objetos.

La biblioteca se carga con:

In [73]:
from numpy import *

Y provee muchas funciones para trabajar con vectores y matrices.


Los vectores se llaman (aunque es un poco confuso) **arrays**, (arreglos) y se pueden crear de distintas maneras. Son como listas, pero con propiedades y **métodos** adicionales para funcionar como objetos matemáticos. La manera más general de crear un vector es justamente convirtiendolo desde una lista de números:

In [74]:
from numpy import *
a = array( [1, 2, -1, 100] )

In [75]:
a

array([  1,   2,  -1, 100])

Un vector de este tipo puede contener sólo un tipo de objetos, a diferencia de una lista normal de *Python*. Si todos los números en la lista son enteros, entonces el tipo del arreglo también lo es, como se puede comprobar con

In [76]:
a.dtype

dtype('int64')

Es común querer crear vectores de cierto tamaño con todos ceros:

In [77]:
b = zeros(10)
print b

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


o todos unos:

In [78]:
b = ones(10)
print b

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


También hay distintas maneras de crear vectores que consisten en rangos ordenados, por ejemplo **`arange`**, que funciona como `range`, con un punto inicial, un punto final, y un paso:

In [79]:
a = arange(0., 10., 0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

y **`linspace`**, donde se especifica puntos iniciales y finales y un número de entradas:

In [81]:
l = linspace(0., 10., 11)
l

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Una notación abreviada para construir vectores es `r_`, que se puede pensar como una abreviación de *“vector renglón”*:


In [83]:
a = r_[1,2,10,-1.]
a

array([ 1.,  2., 10., -1.])

Este método se extiende para dar una manera rápida de construir rangos:

In [84]:
r_[3:7]

array([3, 4, 5, 6])

In [85]:
r_[3:7:0.5]

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [86]:
r_[3:7:10j]

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

Este ultimo utiliza un *número complejo* simplemente como otra notación, y es el equivalente de `linspace(3,7,10)`.

Los vectores creados de esta manera se pueden sumar, restar etc., como si fueran vectores matemáticos. Todas las operaciones se llevan a cabo entrada por entrada:

In [94]:
v1 = array( [1., 4., 7. ])
v2 = array( [1., 2., -2. ])

print v1, v2

[1. 4. 7.] [ 1.  2. -2.]


In [95]:
v1+v2

array([2., 6., 5.])

In [96]:
v1-v2

array([0., 2., 9.])

In [97]:
v1*v2

array([  1.,   8., -14.])

In [98]:
v1/v2

array([ 1. ,  2. , -3.5])

In [99]:
v1**v2

array([ 1.        , 16.        ,  0.02040816])

Las funciones más comunes entre vectores ya están definidas en **numpy**, entre las cuales se encuentran `dot(v1,v2)` para productos escalares de dos vectores de la misma longitud, y `cross(v1,v2)` para el producto cruz de dos vectores de longitud 3.

In [101]:
dot(v1,v2)

-5.0

In [102]:
cross(v1,v2)

array([-22.,   9.,  -2.])

Además, cualquier función matemática como **`sin`** y **`exp`** se puede aplicar directamente a un vector, `y` regresará un vector compuesto por esta función aplicada a cada entrada del vector. Es más: al definir una función el usuario, esta función normalmente también se pueden aplicar directamente a un vector:


In [103]:
def gauss(x):
    return 1./(sqrt(2.)) * exp(-x*x / 2.)

In [104]:
gauss( r_[0:10] )

array([7.07106781e-01, 4.28881942e-01, 9.56964965e-02, 7.85524678e-03,
       2.37207899e-04, 2.63514173e-06, 1.07692220e-08, 1.61908704e-11,
       8.95491734e-15, 1.82204243e-18])

Para extraer subpartes de un vector, la misma sintaxis funciona como para listas: se extraen componentes (entradas) individuales con

In [105]:
a = array([0, 1, 2, 3])
print a[0], a[2]

0 2


y subvectores con

In [106]:
b = a[1:3]
b

array([1, 2])

Nótese, sin embargo, que en este caso la variable `b` no es una copia de esta parte de `a`. Más bien, es una vista de `a`, así que ahora si hacemos:

In [107]:
b[1] = 10

entonces la entrada correspondiente de a ¡también cambia! Este fenómeno también funciona con listas:

In [108]:
l=[1,2,3]; k=l; k[1] = 10

In [109]:
l

[1, 10, 3]

In [110]:
k

[1, 10, 3]

En general, en *Python* las variables son nombres de objetos; al poner `b = a`, **tenemos ¡un mismo objeto con dos nombres!**

## Arreglos numpy (Marices).

Las matrices se tratan como vectores de vectores, o listas de listas:

In [115]:
M = array( [ [1, 2], [3, 4] ] )
M

array([[1, 2],
       [3, 4]])

La forma de la matriz se puede ver con

In [116]:
M.shape

(2, 2)

y se puede manipular con

In [117]:
M.shape = (4, 1)
print M

[[1]
 [2]
 [3]
 [4]]


o con

In [118]:
M.reshape( 2, 2 )

array([[1, 2],
       [3, 4]])

De hecho, eso es una manera util de crear las matrices:

In [120]:
M = r_[0:4].reshape(2,2)

Tambien podemos crear una matriz desde una función:

In [124]:
def f(i, j):
    return i+j

M = fromfunction(f, (3, 3))

M

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

Dado que las matrices son vectores de vectores, al hacer


In [125]:
print M[0]

[0. 1. 2.]


nos regresa la primera componente de M, que es justamente un vector (el primer renglón de M). Si queremos cierta entrada de la matriz, entonces más bien necesitamos especificar dos coordenadas:


In [126]:
M[0][1]

1.0

In [127]:
M[0, 1]

1.0

In [128]:
M.item(1)

1.0

Para extraer ciertas renglones o columnas de `M`, utilizamos una extensión de la notación para vectores:

In [130]:
M = identity(10)

In [131]:
M[3:5]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [132]:
M[:, 3:5]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [133]:
M[3:9, 3:5]     #matriz identidad de 10x10

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Una función poderosa para construir matrices repetidas es tile

In [134]:
tile( M, (2,2) )

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.

Otros métodos útiles son **`diagonal`**, que regresa una diagonal de un arreglo:

In [139]:
diagonal(M)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [140]:
diagonal(M, 1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

y **`diag`**, que construye una matriz con el vector dado como diagonal:

In [141]:
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [142]:
diag([1,2,3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Números aleatorios.

La biblioteca **numpy** incluye un módulo amplio para manipular números aleatorios, llamado **`random`**. Las funciones se llaman, por ejemplo con, `random.random()`. Pero para facilitarnos la vida, podemos importar todas estas funciones al espacio de nombres con:

In [173]:
from random import *   #'random' ya esta cargado!

In [174]:
random?

Nótese que hay otro módulo random que existe afuera de numpy, con distinta funcionalidad. La funcionalidad básica del módulo es la de generar números aleatorios distribuidos de manera uniforme en el intervalo [0, 1):

In [175]:
random()

0.4824629887852161

In [176]:
for i in xrange(10):
    print random()

0.509474717013
0.664012621642
0.260874626126
0.601399656821
0.669943065513
0.376656114696
0.699681417405
0.757896641822
0.527968651758
0.911910366011
